### ISSUE TITLE
Placement in the book?

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/async-trpl-fun#2]
My inclination is to put the new chapter *immediately* after the Fearless Concurrency chapter. That will have given people a lot of the relevant mental machinery for thinking about concurrency in general, and then the async/await stuff can build on it by saying, roughly, “Okay, but threads are expensive, etc. etc. etc.” and use that as a transition into motivation for async/await.

That does also raise the question of how we should *title* it! It’s *even more* concurrency. 😂

**Comment by chriskrycho** [comment]
@carols10cents, what are your thoughts here?

**Comment by carols10cents** [comment]
Hmmm so my thought was we would tack it on to the end, to avoid having to renumber chapters. I don't know if avoiding renumbering is enough of a concern to outweigh where the content makes the most sense?

I'm mostly thinking about blog posts/comments/whatever that are out there on the web where people say (with or without linking) "chapter 18 of the book says blah blah blah" and then we change it so that's now chapter 19 and chapter 18 is something else entirely.

**Comment by chriskrycho** [comment]
Ooooof, yeah, I hadn’t thought of that. That makes sense. The downside is from an actual flow-of-the-book POV, but that may not be worth the cost.

**Comment by chriskrycho** [comment]
Ch 17!
